### ISSUE TITLE
Codebase lacks Backend, Launcher and proper Documentation

### ISSUE THREAD

**Issue by AlexDev404** [AuroraFN/bitwise#1]
Your entire codebase is missing a **backend, launcher and includes _no_ documentation** whatsoever. There are no archives that can be built upon by other people and your _"company"_ contains practically nothing at all and has been wiped clean of your _definitive private server_ and everything that existed along with it. The parser has nothing, too; and I suggest that since your software is aka "closed source" it shouldn't even be on GitHub in the first place. GitHub is a sacred place, and shouldn't be taken as a joke just to promote half-baked projects or something that isn't even partially open-source.

**Comment by Cyuubi** [comment]
There used to be the backend and unified codebase, but was taken down due to skids. This project (bitwise), was intended for a custom game server project I was doing. Plus, I couldn't find *any* actual good bit readers for C#. So, I wrote my own.

As for "parser", it was suppose to be a UE4 packet parser, but, I never got around to working on it unfortunately and I'm too lazy to take down the repo.

**Comment by Cyuubi** [comment]
Also, I'd appreciate if you took down your rehost of our codebase.

**Comment by AlexDev404** [comment]
@Cyuubi :( That's sad. 
Well, unfortunately I can't do that. I am currently working on your codebase as my own personal hobby, and having a lot of fun too. I doubt anybody will come around and *even know* what the codebase is about, as my account isn't really a "popular" account anyway and nobody who really plays Fortnite will even care. Anyway, too bad the unified codebase is gone because now it looks as though I'll have to create my own now. If you really want me to remove the codebase I can just rename it (touché!) and then the problem is fixed. Anyhoo, I hope that cleared things up for you and thanks anyway

**Comment by Cyuubi** [comment]
Geez, no need to be an asshole.

**Comment by AlexDev404** [comment]
Figure it out. It's no mystery.
